### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TomNolane** [ThinhVu/Mmosoft.Facebook.Sdk#1]
Hi! Method LogOn not working. It's get exception LogOnFailureException. But, if attach FacebookAPI.dll logOn is working, but some methods not (such a LikePageTest for example)

**Comment by ThinhVu** [comment]
LikePageTest fail because target page /takeit.me has been suspended. So i think everything still work correctly.
I had refactor current code and make it easier to read.
Note, at the moment, i don't have enough time to test new code.
