### ISSUE TITLE
Problems with special caracters

### ISSUE THREAD

**Issue by danielsgarcia** [ThinhVu/Mmosoft.Facebook.Sdk#3]
Hi!

I had problems with special characters like Á, Ú and others. They are appear as "?".

What could I do to solve this?

Thank you!

**Comment by danielsgarcia** [comment]
I discovered problem can be solved changing encoding in line #99 from HttpHandler class:
Original: byte[] buffer = Encoding.ASCII.GetBytes(content);
Changed: byte[] buffer = Encoding.UTF8.GetBytes(content);

**Comment by ThinhVu** [comment]
Thank you. I'll fix this problem.
