### ISSUE TITLE
header in GetUserGroups method is null

### ISSUE THREAD

**Issue by ghost** [ThinhVu/Mmosoft.Facebook.Sdk#6]
Hello,
var header = BuildDom("https://m.facebook.com/groups/?seemore").SelectSingleNode(xpath);
header is null resulting in broken application!
Looking for help from you!

**Comment by quangcuong10495** [comment]
Sorry I did not type the correct password!
Please delete this  issues!

**Comment by quangcuong10495** [comment]
Sorry I did not type the correct password!
Please delete this  issues!

**Comment by barna21** [comment]
change facebook language in englesh

**Comment by ThinhVu** [comment]
FacebookSDK extract data base on Text content of HTML element. So if the content is not display in English, Facebook SDK will not work correct.
So changing the Facebook language setting to English is the correct answer.

FYI, there is another repository named Facebook-Crawler.
I uploaded this repo in github too (over 9 months ago).

This repository also contain the Facebook SDK code with latest commit (over 9 months ago) to support for language configuration and more helper stuff.

This project is aim to crawl massive public Facebook data so you may find some post methods is missing. But the get methods work very ... nice.

**Comment by barna21** [comment]
Hello,I try to use your code, but when I want to post on the wall and in the group, the code goes over as though it worked, but nothing posts. Can you help me? Do you think you can update the code to make the post part work?Thousands of thanks for your help!

    On Tuesday, February 19, 2019, 8:57:38 AM GMT+2, Thinh Vu <notifications@github.com> wrote:  
 
 
FacebookSDK extract data base on Text content of HTML element. So if the content is not display in English, Facebook SDK will not work correct.
So changing the Facebook language setting to English is the correct answer.

FYI, there is another repository named Facebook-Crawler.
I uploaded this repo in github too (over 9 months ago).

This repository also contain the Facebook SDK code with latest commit (over 9 months ago) to support for language configuration and more helper stuff.

This project is aim to crawl facebook data so you may find some post method is missing. But the get methods work very ... nice.

**Comment by ThinhVu** [comment]
"Hello,I` try to use your code, but when I want to post on the wall and in the group, the code goes over as though it worked, but nothing posts. Can you help me? Do you think you can update the code to make the post part work?Thousands of thanks for your help!"

Seem weird. It's still work as expected with my Facebook account.
https://youtu.be/YxI9Tlpyrz8
