### ISSUE TITLE
Starting scraping

### ISSUE THREAD

**Issue by SyahirahWanMin** [ThinhVu/Mmosoft.Facebook.Sdk#7]
Which file should be run first?

**Comment by leegha019** [comment]
?

**Comment by ThinhVu** [comment]
This is just a library so you can add it into your project. So the answer is depend on your project.
You can also find an example at:
```
https://github.com/ThinhVu/Mmosoft.Facebook.Sdk/blob/master/Mmosoft.Facebook.Sdk.Examples/Program.cs
```
To run this example, fill your fb username, password to UserEndPoint class. 
`var user = new UserEndpoint(username: "", password: "");`
