### ISSUE TITLE
login functionality changed

### ISSUE THREAD

**Issue by ghost** [ThinhVu/Mmosoft.Facebook.Sdk#9]
login functionality changed. It no longer logs in.

**Comment by ThinhVu** [comment]
Thank you for reporting the issue. I'll fix asap.
Can you fix it? If Yes, please make a pull request. It'll help me alot.

**Comment by ghost** [comment]
I had a little look but i couldn't figure it out unfortunately. I think it's to do with this 'remember device' setting, but im unsure.

I can tell you that the c_user cookie is null, which is why the code falls over and the exception is thrown.

Facebook didnt rename or change the c_user cookie, it still exists, its just not getting set. The code pulls all the form values from the page like before, so maybe its a header issue, script issue or something else?

**Comment by ghost** [comment]
That is all i can figure out

**Comment by ghost** [comment]
Any luck?

it would be a shame for this API to stop working. Lots of effort was put into it!

**Comment by AnthonyMusgrove** [comment]
The example is working fine.  Put in my facebook email and password,

![facebook sdk working](https://user-images.githubusercontent.com/55648663/80308408-33ea3f80-8812-11ea-9e40-fa1be910de6e.PNG)

**Comment by ghost** [comment]
Looks like it has magically started working again *shrug*

Lets hope nothing else goes wrong, I think the dev has stopped this project

**Comment by AnthonyMusgrove** [comment]
Im more then happy to continue this project and spend the time working  on additional features (i need heapsof extras).  Check out my github, ill fork it soon

**Comment by ghost** [comment]
That would be neat! Thank you!

**Comment by ghost** [comment]
I did notice that when posting via the API, i get my account locked because it thinks somebody has my password. I have to keep resetting it over and over again.

Maybe ill create a new issue

Your Account is Temporarily Locked
We’ve detected suspicious activity on your Facebook account and have temporarily locked it as a security precaution.
It’s likely that your account was compromised as a result of entering your password on a website designed to look like Facebook. This type of attack is known as phishing. Learn more in the Help Center.
Over the next few steps we’ll walk you through a security check to help secure your account, and let you log back in.
